Repository toonarmycaptain/dionysus, pull requests merged in 2018-10, with the labels that each got.

#7 Update deps
  requirements.txt
Labels: size/XS

#13 Update app_main.py
  app_main.py
Labels: size/XS, status/ci-approved

#20 Add Appveyor config file
  .appveyor.yml
Labels: size/XS, status/ci-approved

#23 Add Coveralls configuration (#22)
  .coveragerc
  .travis.yml
Labels: size/XS, status/ci-approved

#24 Fix Coveralls configuration
  .travis.yml
Labels: size/XS

#26 Use JSON for class data
  dionysus_app/class_functions.py
Labels: size/XS

#29 Add docstrings to class_functions.py
  dionysus_app/class_functions.py
Labels: size/XS, status/ci-approved

#32 Switch to JSON
  dionysus_app/class_functions.py
Labels: size/S, status/ci-approved

#35 Expand class registry
  .codacy.yml
  CONTRIBUTING.md
  README.md
  app_main.py
  dionysus_app/class_functions.py
  dionysus_app/class_registry.py
Labels: size/S

#36 Update requirements.txt
  requirements.txt
Labels: size/XS

#37 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#38 Catchup to master
  CONTRIBUTING.md
  dionysus_app/class_functions.py
  requirements.txt
Labels: size/XS

#39 Catchup to master.
  CONTRIBUTING.md
  dionysus_app/class_functions.py
  requirements.txt
Labels: size/XS

#41 Expand class registry
  CONTRIBUTING.md
  dionysus_app/class_functions.py
  dionysus_app/class_registry.py
  test_suite/test_class_registry.py
Labels: size/S
